name: Build macOS App (Universal with Qt Build)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # НОВЫЙ ШАГ: Устанавливаем инструменты для сборки Qt
      - name: Install Qt5 development tools
        run: brew install qt@5

      - name: Install dependencies (with universal CFFI & PyQt5 fix)
        env:
          ARCHFLAGS: "-arch arm64 -arch x86_64"
        run: |
          python -m pip install --upgrade pip
          # Говорим pip не использовать готовые бинарники
          pip install --no-binary :all: -r requirements.txt
          pip install pyinstaller

      - name: Build CONSOLE .app with PyInstaller
        run: |
          pyinstaller --name "tldv-extract" \
                      --onefile \
                      --add-data "templates:templates" \
                      --target-arch universal2 \
                      app.py

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App-Universal-Debug
          path: dist/tldv-extract.app