name: Build macOS App (Debug Mode)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Собираем на Intel, это наш самый надежный вариант
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # ГЛАВНОЕ ИЗМЕНЕНИЕ: Собираем без флага --windowed
      - name: Build CONSOLE .app with PyInstaller
        run: |
          pyinstaller --name "tldv-extract" \
                      --onefile \
                      --add-data "templates:templates" \
                      app.py

      # Мы не будем создавать .dmg, чтобы упростить процесс.
      # Мы просто запакуем .app в zip-архив.
      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App-Debug
          path: dist/tldv-extract.app