name: Build macOS App for Intel (x86_64)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # ИЗМЕНЕНИЕ 1: Возвращаем современный, быстрый runner, который всегда доступен.
    runs-on: macos-latest

    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. Собираем .app приложение
      - name: Build .app with PyInstaller for Intel
        run: |
          # ИЗМЕНЕНИЕ 2: Четко указываем цель - Intel (x86_64).
          # Это решит проблему "не поддерживается на этом компьютере".
          pyinstaller --name "tldv-extract" \
                      --onefile \
                      --windowed \
                      --add-data "templates:templates" \
                      --target-arch x86_64 \
                      app.py

      # 5. Создаем .dmg установщик
      - name: Create DMG Installer
        run: |
          brew install create-dmg
          create-dmg \
            --volname "tldv-extract Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "tldv-extract.app" 200 190 \
            --hide-extension "tldv-extract.app" \
            --app-drop-link 600 185 \
            "dist/tldv-extract.dmg" \
            "dist/tldv-extract.app"

      # 6. Загружаем готовый .dmg
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Intel-Installer
          path: dist/tldv-extract.dmg