name: Build macOS App (Universal Fix)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Возвращаемся на быстрый и доступный runner
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ГЛАВНОЕ ИЗМЕНЕНИЕ ЗДЕСЬ
      - name: Install dependencies (with universal CFFI fix)
        env:
          # Говорим компилятору создавать универсальные бинарники
          ARCHFLAGS: "-arch arm64 -arch x86_64"
        run: |
          python -m pip install --upgrade pip
          # Говорим pip НЕ скачивать готовый cffi, а собрать его с нуля
          pip install --no-binary cffi cffi
          # Теперь устанавливаем все остальное
          pip install -r requirements.txt
          pip install pyinstaller

      # Собираем в отладочном режиме (без --windowed), чтобы видеть ошибки
      - name: Build CONSOLE .app with PyInstaller
        run: |
          pyinstaller --name "tldv-extract" \
                      --onefile \
                      --add-data "templates:templates" \
                      --target-arch universal2 \
                      app.py

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App-Universal-Debug
          path: dist/tldv-extract.app